#!/bin/bash

file_="/etc/group"
groupname=

while [ ! -z $1 ]
do
    if [ "$1" == "-"* ]
    then
	if [ "$1" == "-f" ] && [ ! -z "$2" ]
	then
	    file_="$2"
	else
	    echo "Error" >&2
	fi
    else
	groupname="$1"
    fi
    shift
done

if [ -z $groupname ] 
then
    echo "Error"  >&2
    exit 2
fi

if [ -f $file_ ]
then
    path=`grep "^$groupname:" "$file_" | cut -d':' -f4`
    echo "Users are:"
    echo "$path" | sed s/,/\\n/g
    exit 0
else
    echo "File does not exist" >&2
    exit 2
fi
